source: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

In [1]:
from __future__ import print_function
import torch

In [2]:
# 创建0矩阵
x = torch.empty(3,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [3]:
x = torch.rand(3,3)
x

tensor([[0.8492, 0.4235, 0.7314],
        [0.4326, 0.3560, 0.5524],
        [0.7488, 0.5944, 0.6094]])

In [4]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.4253,  0.9696,  0.5134],
        [ 0.4096,  0.1529, -0.5618],
        [-0.8013, -0.5498,  1.6129],
        [ 0.1187,  0.5430,  0.8277],
        [-0.0275, -0.5228, -2.8311]])


In [5]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[ 2.4253,  1.9696,  1.5134],
        [ 1.4096,  1.1529,  0.4382],
        [ 0.1987,  0.4502,  2.6129],
        [ 1.1187,  1.5430,  1.8277],
        [ 0.9725,  0.4772, -1.8311]], device='cuda:0')
tensor([[ 2.4253,  1.9696,  1.5134],
        [ 1.4096,  1.1529,  0.4382],
        [ 0.1987,  0.4502,  2.6129],
        [ 1.1187,  1.5430,  1.8277],
        [ 0.9725,  0.4772, -1.8311]], dtype=torch.float64)
